#!/data/data/com.termux/files/usr/bin/bash
# Auto Install Tools Hack Facebook V3
# coded By Ro0TP00R 

clear

blue='\e[0;34'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

###################################################
# CTRL C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red" GOOD BYE " 
sleep 1
echo ""
echo -e $green" SILAHKAN EDIT TOOLS INI TAPI JANGAN LUPA HACK CIPTA"
sleep 1
echo ""
echo -e $yellow" SALAM NEWBY "
read enter
exit
}


echo -e $red" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e $red" ⟨⟩" $yellow" Code"        ㅤ ㅤ$red":" $lightgreen"Ro0TP00R"$red">>>>>>>>>>>>"
echo -e $red" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e $red" ⟨⟩" $yellow" YT"     ㅤ   ㅤㅤ$red":" $lightgreen"Tutorial Termux AC"$red">>"
echo -e $red" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e $red" ⟨⟩" $yellow" WA"        ㅤㅤ ㅤ$red":" $lightgreen"Banyak di Google"$red">>>>"
echo -e $red" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e $red" ⟨⟩" $yellow" GitHun"         ㅤ $red":" $lightgreen"Ro0TP00R777Channel"$red">>"
echo -e $red" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e $red" ⟨⟩" $yellow" Versi"ㅤ ㅤ$red":" $lightgreen"V3"$red">>>>>>>>>>>>>>>>>>"
echo -e $red" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"

echo ""
echo -e $cyan" Kumpulan Tools Hack Facebook"
echo -e $red" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e $red" ⟨⟩" $green" ["$lightgreen"01"$green"]"  "$yellow" INSTALL DULU BAHAN       $red"   ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"02"$green"]"  "$yellow" Fbv3     $red"                 ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"03"$green"]"  "$yellow" DarkFb V1.7  $red"          ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"04"$green"]"  "$yellow" DarkCurut08    $red"          ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"05"$green"]"  "$yellow" Facebook Cracker V2   $red"  ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"06"$green"]"  "$yellow" MBF   $red"                  ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"07"$green"]"  "$yellow" Fb-Brute    $red"             ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"08"$green"]"  "$yellow" Fb-hack    $red"              ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"09"$green"]"  "$yellow" Fb-group-hack    $red"        ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"10"$green"]"  "$yellow" Fb-hacker    $red"            ⟨⟩" 
echo -e $red" ⟨⟩" $green" ["$lightgreen"11"$green"]"  "$yellow" EXIT    $red"                 ⟨⟩" 
echo -e $red" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo -e $white""
echo -e "╭>Dipilih Harga Murah" |lolcat
read -p "╰─»" act;

if [ $act = 01 ] || [ $act = 01 ]
then
clear
echo -e $cyan" Install Dulu Bahan BOS!! "
sleep 1
apt update -y
apt upgrade -y
pkg install python -y
pkg install python2 -y
pip2 install requests -y
pip2 install mechanize -y
pkg install php -y
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 02 ] || [ $act = 02 ]
then
clear
echo -e $cyan" Langsung Ke Git Clone "
git clone https://github.com/Ro0TP00R777Channel/fbv3
cd fbv4
python2 fbv3.py
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 03 ] || [ $act = 03 ]
then
clear
echo -e $cyan" Langsung Ke Git Clone "
git clone https://github.com/storiku/darkfb
cd darkfb
python2 Dark.py
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 04 ] || [ $act = 04 ]
then
clear
echo -e $cyan" Langsung Ke Git Clone "
git clone https://github.com/DarkCurut08/DarkCurut08
cd DarkCurut08
sh Moreno77.sh
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 05 ] || [ $act = 05 ]
then
clear
echo -e $cyan" Langsung Ke Git Clone "
curl -S https://pastebin.com/raw/yUpg8zsv --output fb.py
python2 fb.py
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 06 ] || [ $act = 06 ]
then
clear
echo -e $cyan" Langsung Ke Git Clone "
git clone https://github.com/pirmansx/mbf
cd mbf
python2 mbf.py
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 07 ] || [ $act = 07 ]
then
clear
echo -e $cyan" Langsung Ke Git Clone "
git clone https://github.com/IqbalDev/fb-brute
cd fb-brute
python2 brute.py
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 08 ] || [ $act = 08 ]
then
clear
echo -e $cyan" Langsung Ke Git Clone "
git clone https://github.com/pashayogi/Fb-hack
cd Fb-hack
python2 FB-HACK.py
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 09 ] || [ $act = 09 ]
then
clear
echo -e $cyan" Langsung Ke Git Clone "
git clone https://github.com/Mr-NemrMedo/fb-group-hack
cd fb-group-hack
python2 fb-group-hack.py
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 10 ] || [ $act = 10 ]
then
clear
echo -e $cyan" Langsung Ke Git Clone "
git clone https://github.com/V4N654T/fb-hacker
cd fb-hacker
python2 fb.py
echo -e $cyan" Done Install Cuk "
fi

if [ $act = 11 ] || [ $act = 11 ]
then
echo -e $red" Pesan Terakhir "
sleep 1
echo -e $cyan" Kalian kagum dan bertanya – tanya. Siapa Aku Sebenarnya. Inilah Aku. Orang yang pernah kalian hina dimasa lalu. "
sleep 1
echo -e $green" Ketakutan memberi kecerdasan bahkan pada orang bodoh. "
sleep 1
echo -e $lightgreen" Dalam setiap bisnis selalu ada seseorang yang tahu persis apa yang sedang terjadi. Dan orang itu harus dipecat. "
sleep 1
echo -e $okegreen" Kamu Hagai Saya. Saya Hagai Kamu."
sleep 1
echo -e $yellow" Selamat Baca :) "
sleep 1
exit
fi